### ISSUE TITLE
App will crash on devices without flash

### ISSUE THREAD

**Issue by EddyVerbruggen** [tjvantoll/nativescript-flashlight#2]
Hi TJ,

I just tried the plugin on a Nexus 7 (2012 model) which doesn't have a camera. [This line](https://github.com/tjvantoll/nativescript-flashlight/blob/master/flashlight.android.js#L3) will crash the app.

Moving the line into the `on`/`off` functions fixes the crash (it will of course still crash in case the camera is switched on for that same device). You may want to consider adding a function for checking camera availability, and perhaps wrapping the functions in try-catch blocks.

In case you can't fix it anytime soon I will take a shot myself.

Thanks,
Eddy

**Comment by tjvantoll** [comment]
Hey Eddy,

Thanks for this and sorry I just saw it. I do plan on adding an `available` method of some sorts to match your Cordova plugin. I'll take a stab at it later this weekend.

**Comment by EddyVerbruggen** [comment]
:+1:
