### ISSUE TITLE
Close the Camera after opening it

### ISSUE THREAD

**Issue by atanasovg** [tjvantoll/nativescript-flashlight#3]
Hey @tjvantoll, you may want to close the Camera once the flashlight is off, otherwise it will remain locked for other applications that may want to use it:

>You must call release() when you are done using the camera, otherwise it will remain locked and be unavailable to other applications.

[Camera API](http://developer.android.com/reference/android/hardware/Camera.html#open(int))

**Comment by tjvantoll** [comment]
Thanks @atanasovg!

I added a call to `release()` in `off()` and published 1.0.1.
