### ISSUE TITLE
Create a `.d.ts` file for TypeScript users

### ISSUE THREAD

**Issue by tjvantoll** [tjvantoll/nativescript-flashlight#5]

**Comment by bradmartin** [comment]
Have it to you soon :)

**Comment by bradmartin** [comment]
https://github.com/tjvantoll/nativescript-flashlight/pull/6 - needs testing. Also, a note about Android 6.0 permissions at runtime might be good to add to the README. No time to do it tonight, but this should be a start for the TS support.

**Comment by tjvantoll** [comment]
Closed with #6. Thanks!
